### ISSUE TITLE
测试服务发现时遇到的问题

### ISSUE THREAD

**Issue by ReReniao** [1055373165/ggcache#8]
启动test.sh后，起了三个节点9999,10000,10001，创建同名group：scores，在测试服务发现用例serverRegisterCall时，报错：
```shell
err: rpc error: code = Unknown desc = group scores not found
```

**Comment by 1055373165** [comment]
run.sh 这个脚本可以正常启动是吧？我当时为了测试效果依赖了数据库，你可以在 main.go 的 NewGroupInstance 中将数据库的依赖移除，然后使用一个 map 模拟数据库再试一下；最近正在重新优化一些代码，原来的 etcd 3.5.9 版本有个 bug，你如果遇到了再说。

**Comment by 1055373165** [comment]
<img width="702" alt="image" src="https://github.com/1055373165/Distributed_KV_Store/assets/33158355/a37a8072-47d4-439a-83a2-f20bb3d76e01">

刚刚测试了下，节点间 rpc 通信服务没什么问题，你上面那个问题是测试用例中没有对 record not found 的特殊情况进行处理；根据服务端的返回构造特殊 ERR 类型进行判断处理就可以了。

**Comment by ReReniao** [comment]
我也实现了本地DB，报这个错误是在Server.Get(),从rpc获取到group的name，服务结点getGroup的时候报错，并没有走到去数据库fetcher的逻辑，照理说三个节点都是同名的group不应该在注册后还返回nil

**Comment by ReReniao** [comment]
我也跟着您重构了代码，目前测试用例都可以通过，大佬可以增加这部分的测试用例，看看能不能复现

**Comment by 1055373165** [comment]
我在 master 分支上重新写了一下测试用例，你看看参考一下
